# Generated by Django 3.1.3 on 2022-05-18 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20220517_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_create',
            new_name='create_date',
        ),
    ]
