# Generated by Django 3.1.3 on 2022-06-10 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_questioncount'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questioncount',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_answer', to='pybo.question'),
        ),
    ]
