# Generated by Django 3.1.3 on 2022-06-10 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0011_question_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncount',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.question'),
        ),
    ]
