# Generated by Django 3.1.3 on 2022-06-10 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0012_auto_20220610_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='view',
        ),
        migrations.DeleteModel(
            name='QuestionCount',
        ),
    ]
