# Generated by Django 3.1.3 on 2022-06-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0015_question_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='view',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
